name: flutter_app #name是包的名称
description: A new Flutter application.

dependencies: #dependencies是需要依赖的包名   执行pub get命令下载相关依赖包
  flutter:
    sdk: flutter
  url_launcher: 3.0.3
  path_provider: 0.4.1
  fluro: ^1.3.4
  rxdart: ^0.19.0
  dio: 1.0.6
   # 弹吐司
  fluttertoast: ^2.0.3
  http: ^0.12.0
  web_socket_channel: ^1.0.9
  # 选择图片
  image_picker: ^0.4.10
  # 视频播放
  video_player: ^0.7.2
  #图像查看和手势缩放功能
  zoomable_image: ^1.2.1+1
  #一个支持手势划动和自动播放的图像展示控件。
  carousel_slider: ^0.0.7
  #视频播放器，在video_player的基础上包装了控制UI。
  chewie: ^0.8.0
  #英语单词包
  english_words: ^3.1.5
  #下拉刷新上拉加载更多
  pull_to_refresh: ^1.1.6
  #下拉刷新
  flutter_refresh : ^0.0.1
  #粘性头部
  flutter_sticky_header: ^0.3.4

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_localizations: #flutter国际化依赖
      sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - images/timg.jpg
    - images/ic_nav_discover_actived.png
    - images/ic_nav_discover_normal.png
    - images/ic_nav_my_normal.png
    - images/ic_nav_my_pressed.png
    - images/ic_nav_news_actived.png
    - images/ic_nav_news_normal.png
    - images/ic_nav_tweet_actived.png
    - images/ic_nav_tweet_normal.png
    - images/leftmenu/ic_xiaoheiwu.png
    - images/leftmenu/ic_fabu.png
    - images/leftmenu/ic_about.png
    - images/leftmenu/ic_settings.png
    - images/cover_img.jpg
    - images/ic_arrow_right.png
    - images/lifecycle.png
    - assets/flutter-mark-square-64.png
    - assets/Butterfly-209.mp4

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
